version: "3.8"


services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    restart: always
    privileged: true
    user: root
    tty: true
    stdin_open: true
    ports:
      - 8090:8080
      - 50000:50000
    container_name: "jenkins"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_turismo
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  jenkins_home:
  mysql_data: